// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwgVx4Usy61WBYwiP7dehdMqAaTjosjH0',
    appId: '1:626218295278:web:2b1c147d2e30089cc338ff',
    messagingSenderId: '626218295278',
    projectId: 'komik-app-e7611',
    authDomain: 'komik-app-e7611.firebaseapp.com',
    storageBucket: 'komik-app-e7611.appspot.com',
    measurementId: 'G-8C34T80472',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8y16R6r4m-vkQYJPvOeZpjYqO9bm_ffU',
    appId: '1:626218295278:android:ff2dab87e5579498c338ff',
    messagingSenderId: '626218295278',
    projectId: 'komik-app-e7611',
    storageBucket: 'komik-app-e7611.appspot.com',
  );
}
